// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/iaasalpha (interfaces: DefaultApi)
//
// Generated by this command:
//
//	mockgen -destination=./mock/v2/client.go -package=mock_network_v2 github.com/stackitcloud/stackit-sdk-go/services/iaasalpha DefaultApi
//

// Package mock_network_v2 is a generated GoMock package.
package mock_network_v2

import (
	context "context"
	reflect "reflect"

	iaasalpha "github.com/stackitcloud/stackit-sdk-go/services/iaasalpha"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultApi is a mock of DefaultApi interface.
type MockDefaultApi struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultApiMockRecorder
	isgomock struct{}
}

// MockDefaultApiMockRecorder is the mock recorder for MockDefaultApi.
type MockDefaultApiMockRecorder struct {
	mock *MockDefaultApi
}

// NewMockDefaultApi creates a new mock instance.
func NewMockDefaultApi(ctrl *gomock.Controller) *MockDefaultApi {
	mock := &MockDefaultApi{ctrl: ctrl}
	mock.recorder = &MockDefaultApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultApi) EXPECT() *MockDefaultApiMockRecorder {
	return m.recorder
}

// AddRoutesToRoutingTable mocks base method.
func (m *MockDefaultApi) AddRoutesToRoutingTable(ctx context.Context, organizationId, areaId, region, routingTableId string) iaasalpha.ApiAddRoutesToRoutingTableRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoutesToRoutingTable", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(iaasalpha.ApiAddRoutesToRoutingTableRequest)
	return ret0
}

// AddRoutesToRoutingTable indicates an expected call of AddRoutesToRoutingTable.
func (mr *MockDefaultApiMockRecorder) AddRoutesToRoutingTable(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoutesToRoutingTable", reflect.TypeOf((*MockDefaultApi)(nil).AddRoutesToRoutingTable), ctx, organizationId, areaId, region, routingTableId)
}

// AddRoutesToRoutingTableExecute mocks base method.
func (m *MockDefaultApi) AddRoutesToRoutingTableExecute(ctx context.Context, organizationId, areaId, region, routingTableId string) (*iaasalpha.RouteListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoutesToRoutingTableExecute", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(*iaasalpha.RouteListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRoutesToRoutingTableExecute indicates an expected call of AddRoutesToRoutingTableExecute.
func (mr *MockDefaultApiMockRecorder) AddRoutesToRoutingTableExecute(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoutesToRoutingTableExecute", reflect.TypeOf((*MockDefaultApi)(nil).AddRoutesToRoutingTableExecute), ctx, organizationId, areaId, region, routingTableId)
}

// AddRoutingTableToArea mocks base method.
func (m *MockDefaultApi) AddRoutingTableToArea(ctx context.Context, organizationId, areaId, region string) iaasalpha.ApiAddRoutingTableToAreaRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoutingTableToArea", ctx, organizationId, areaId, region)
	ret0, _ := ret[0].(iaasalpha.ApiAddRoutingTableToAreaRequest)
	return ret0
}

// AddRoutingTableToArea indicates an expected call of AddRoutingTableToArea.
func (mr *MockDefaultApiMockRecorder) AddRoutingTableToArea(ctx, organizationId, areaId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoutingTableToArea", reflect.TypeOf((*MockDefaultApi)(nil).AddRoutingTableToArea), ctx, organizationId, areaId, region)
}

// AddRoutingTableToAreaExecute mocks base method.
func (m *MockDefaultApi) AddRoutingTableToAreaExecute(ctx context.Context, organizationId, areaId, region string) (*iaasalpha.RoutingTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoutingTableToAreaExecute", ctx, organizationId, areaId, region)
	ret0, _ := ret[0].(*iaasalpha.RoutingTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRoutingTableToAreaExecute indicates an expected call of AddRoutingTableToAreaExecute.
func (mr *MockDefaultApiMockRecorder) AddRoutingTableToAreaExecute(ctx, organizationId, areaId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoutingTableToAreaExecute", reflect.TypeOf((*MockDefaultApi)(nil).AddRoutingTableToAreaExecute), ctx, organizationId, areaId, region)
}

// CreateNetwork mocks base method.
func (m *MockDefaultApi) CreateNetwork(ctx context.Context, projectId, region string) iaasalpha.ApiCreateNetworkRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, projectId, region)
	ret0, _ := ret[0].(iaasalpha.ApiCreateNetworkRequest)
	return ret0
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockDefaultApiMockRecorder) CreateNetwork(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockDefaultApi)(nil).CreateNetwork), ctx, projectId, region)
}

// CreateNetworkExecute mocks base method.
func (m *MockDefaultApi) CreateNetworkExecute(ctx context.Context, projectId, region string) (*iaasalpha.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetworkExecute", ctx, projectId, region)
	ret0, _ := ret[0].(*iaasalpha.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetworkExecute indicates an expected call of CreateNetworkExecute.
func (mr *MockDefaultApiMockRecorder) CreateNetworkExecute(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetworkExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateNetworkExecute), ctx, projectId, region)
}

// DeleteNetwork mocks base method.
func (m *MockDefaultApi) DeleteNetwork(ctx context.Context, projectId, region, networkId string) iaasalpha.ApiDeleteNetworkRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", ctx, projectId, region, networkId)
	ret0, _ := ret[0].(iaasalpha.ApiDeleteNetworkRequest)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockDefaultApiMockRecorder) DeleteNetwork(ctx, projectId, region, networkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockDefaultApi)(nil).DeleteNetwork), ctx, projectId, region, networkId)
}

// DeleteNetworkExecute mocks base method.
func (m *MockDefaultApi) DeleteNetworkExecute(ctx context.Context, projectId, region, networkId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworkExecute", ctx, projectId, region, networkId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetworkExecute indicates an expected call of DeleteNetworkExecute.
func (mr *MockDefaultApiMockRecorder) DeleteNetworkExecute(ctx, projectId, region, networkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworkExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteNetworkExecute), ctx, projectId, region, networkId)
}

// DeleteRouteFromRoutingTable mocks base method.
func (m *MockDefaultApi) DeleteRouteFromRoutingTable(ctx context.Context, organizationId, areaId, region, routingTableId, routeId string) iaasalpha.ApiDeleteRouteFromRoutingTableRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRouteFromRoutingTable", ctx, organizationId, areaId, region, routingTableId, routeId)
	ret0, _ := ret[0].(iaasalpha.ApiDeleteRouteFromRoutingTableRequest)
	return ret0
}

// DeleteRouteFromRoutingTable indicates an expected call of DeleteRouteFromRoutingTable.
func (mr *MockDefaultApiMockRecorder) DeleteRouteFromRoutingTable(ctx, organizationId, areaId, region, routingTableId, routeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRouteFromRoutingTable", reflect.TypeOf((*MockDefaultApi)(nil).DeleteRouteFromRoutingTable), ctx, organizationId, areaId, region, routingTableId, routeId)
}

// DeleteRouteFromRoutingTableExecute mocks base method.
func (m *MockDefaultApi) DeleteRouteFromRoutingTableExecute(ctx context.Context, organizationId, areaId, region, routingTableId, routeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRouteFromRoutingTableExecute", ctx, organizationId, areaId, region, routingTableId, routeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRouteFromRoutingTableExecute indicates an expected call of DeleteRouteFromRoutingTableExecute.
func (mr *MockDefaultApiMockRecorder) DeleteRouteFromRoutingTableExecute(ctx, organizationId, areaId, region, routingTableId, routeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRouteFromRoutingTableExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteRouteFromRoutingTableExecute), ctx, organizationId, areaId, region, routingTableId, routeId)
}

// DeleteRoutingTableFromArea mocks base method.
func (m *MockDefaultApi) DeleteRoutingTableFromArea(ctx context.Context, organizationId, areaId, region, routingTableId string) iaasalpha.ApiDeleteRoutingTableFromAreaRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoutingTableFromArea", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(iaasalpha.ApiDeleteRoutingTableFromAreaRequest)
	return ret0
}

// DeleteRoutingTableFromArea indicates an expected call of DeleteRoutingTableFromArea.
func (mr *MockDefaultApiMockRecorder) DeleteRoutingTableFromArea(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoutingTableFromArea", reflect.TypeOf((*MockDefaultApi)(nil).DeleteRoutingTableFromArea), ctx, organizationId, areaId, region, routingTableId)
}

// DeleteRoutingTableFromAreaExecute mocks base method.
func (m *MockDefaultApi) DeleteRoutingTableFromAreaExecute(ctx context.Context, organizationId, areaId, region, routingTableId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoutingTableFromAreaExecute", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoutingTableFromAreaExecute indicates an expected call of DeleteRoutingTableFromAreaExecute.
func (mr *MockDefaultApiMockRecorder) DeleteRoutingTableFromAreaExecute(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoutingTableFromAreaExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteRoutingTableFromAreaExecute), ctx, organizationId, areaId, region, routingTableId)
}

// GetNetwork mocks base method.
func (m *MockDefaultApi) GetNetwork(ctx context.Context, projectId, region, networkId string) iaasalpha.ApiGetNetworkRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetwork", ctx, projectId, region, networkId)
	ret0, _ := ret[0].(iaasalpha.ApiGetNetworkRequest)
	return ret0
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockDefaultApiMockRecorder) GetNetwork(ctx, projectId, region, networkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockDefaultApi)(nil).GetNetwork), ctx, projectId, region, networkId)
}

// GetNetworkExecute mocks base method.
func (m *MockDefaultApi) GetNetworkExecute(ctx context.Context, projectId, region, networkId string) (*iaasalpha.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkExecute", ctx, projectId, region, networkId)
	ret0, _ := ret[0].(*iaasalpha.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkExecute indicates an expected call of GetNetworkExecute.
func (mr *MockDefaultApiMockRecorder) GetNetworkExecute(ctx, projectId, region, networkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetNetworkExecute), ctx, projectId, region, networkId)
}

// GetRouteOfRoutingTable mocks base method.
func (m *MockDefaultApi) GetRouteOfRoutingTable(ctx context.Context, organizationId, areaId, region, routingTableId, routeId string) iaasalpha.ApiGetRouteOfRoutingTableRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteOfRoutingTable", ctx, organizationId, areaId, region, routingTableId, routeId)
	ret0, _ := ret[0].(iaasalpha.ApiGetRouteOfRoutingTableRequest)
	return ret0
}

// GetRouteOfRoutingTable indicates an expected call of GetRouteOfRoutingTable.
func (mr *MockDefaultApiMockRecorder) GetRouteOfRoutingTable(ctx, organizationId, areaId, region, routingTableId, routeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteOfRoutingTable", reflect.TypeOf((*MockDefaultApi)(nil).GetRouteOfRoutingTable), ctx, organizationId, areaId, region, routingTableId, routeId)
}

// GetRouteOfRoutingTableExecute mocks base method.
func (m *MockDefaultApi) GetRouteOfRoutingTableExecute(ctx context.Context, organizationId, areaId, region, routingTableId, routeId string) (*iaasalpha.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteOfRoutingTableExecute", ctx, organizationId, areaId, region, routingTableId, routeId)
	ret0, _ := ret[0].(*iaasalpha.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteOfRoutingTableExecute indicates an expected call of GetRouteOfRoutingTableExecute.
func (mr *MockDefaultApiMockRecorder) GetRouteOfRoutingTableExecute(ctx, organizationId, areaId, region, routingTableId, routeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteOfRoutingTableExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetRouteOfRoutingTableExecute), ctx, organizationId, areaId, region, routingTableId, routeId)
}

// GetRoutingTableOfArea mocks base method.
func (m *MockDefaultApi) GetRoutingTableOfArea(ctx context.Context, organizationId, areaId, region, routingTableId string) iaasalpha.ApiGetRoutingTableOfAreaRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutingTableOfArea", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(iaasalpha.ApiGetRoutingTableOfAreaRequest)
	return ret0
}

// GetRoutingTableOfArea indicates an expected call of GetRoutingTableOfArea.
func (mr *MockDefaultApiMockRecorder) GetRoutingTableOfArea(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutingTableOfArea", reflect.TypeOf((*MockDefaultApi)(nil).GetRoutingTableOfArea), ctx, organizationId, areaId, region, routingTableId)
}

// GetRoutingTableOfAreaExecute mocks base method.
func (m *MockDefaultApi) GetRoutingTableOfAreaExecute(ctx context.Context, organizationId, areaId, region, routingTableId string) (*iaasalpha.RoutingTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutingTableOfAreaExecute", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(*iaasalpha.RoutingTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoutingTableOfAreaExecute indicates an expected call of GetRoutingTableOfAreaExecute.
func (mr *MockDefaultApiMockRecorder) GetRoutingTableOfAreaExecute(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutingTableOfAreaExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetRoutingTableOfAreaExecute), ctx, organizationId, areaId, region, routingTableId)
}

// ListNetworks mocks base method.
func (m *MockDefaultApi) ListNetworks(ctx context.Context, projectId, region string) iaasalpha.ApiListNetworksRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks", ctx, projectId, region)
	ret0, _ := ret[0].(iaasalpha.ApiListNetworksRequest)
	return ret0
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockDefaultApiMockRecorder) ListNetworks(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockDefaultApi)(nil).ListNetworks), ctx, projectId, region)
}

// ListNetworksExecute mocks base method.
func (m *MockDefaultApi) ListNetworksExecute(ctx context.Context, projectId, region string) (*iaasalpha.NetworkListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworksExecute", ctx, projectId, region)
	ret0, _ := ret[0].(*iaasalpha.NetworkListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworksExecute indicates an expected call of ListNetworksExecute.
func (mr *MockDefaultApiMockRecorder) ListNetworksExecute(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworksExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListNetworksExecute), ctx, projectId, region)
}

// ListRoutesOfRoutingTable mocks base method.
func (m *MockDefaultApi) ListRoutesOfRoutingTable(ctx context.Context, organizationId, areaId, region, routingTableId string) iaasalpha.ApiListRoutesOfRoutingTableRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutesOfRoutingTable", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(iaasalpha.ApiListRoutesOfRoutingTableRequest)
	return ret0
}

// ListRoutesOfRoutingTable indicates an expected call of ListRoutesOfRoutingTable.
func (mr *MockDefaultApiMockRecorder) ListRoutesOfRoutingTable(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutesOfRoutingTable", reflect.TypeOf((*MockDefaultApi)(nil).ListRoutesOfRoutingTable), ctx, organizationId, areaId, region, routingTableId)
}

// ListRoutesOfRoutingTableExecute mocks base method.
func (m *MockDefaultApi) ListRoutesOfRoutingTableExecute(ctx context.Context, organizationId, areaId, region, routingTableId string) (*iaasalpha.RouteListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutesOfRoutingTableExecute", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(*iaasalpha.RouteListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoutesOfRoutingTableExecute indicates an expected call of ListRoutesOfRoutingTableExecute.
func (mr *MockDefaultApiMockRecorder) ListRoutesOfRoutingTableExecute(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutesOfRoutingTableExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListRoutesOfRoutingTableExecute), ctx, organizationId, areaId, region, routingTableId)
}

// ListRoutingTablesOfArea mocks base method.
func (m *MockDefaultApi) ListRoutingTablesOfArea(ctx context.Context, organizationId, areaId, region string) iaasalpha.ApiListRoutingTablesOfAreaRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutingTablesOfArea", ctx, organizationId, areaId, region)
	ret0, _ := ret[0].(iaasalpha.ApiListRoutingTablesOfAreaRequest)
	return ret0
}

// ListRoutingTablesOfArea indicates an expected call of ListRoutingTablesOfArea.
func (mr *MockDefaultApiMockRecorder) ListRoutingTablesOfArea(ctx, organizationId, areaId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutingTablesOfArea", reflect.TypeOf((*MockDefaultApi)(nil).ListRoutingTablesOfArea), ctx, organizationId, areaId, region)
}

// ListRoutingTablesOfAreaExecute mocks base method.
func (m *MockDefaultApi) ListRoutingTablesOfAreaExecute(ctx context.Context, organizationId, areaId, region string) (*iaasalpha.RoutingTableListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutingTablesOfAreaExecute", ctx, organizationId, areaId, region)
	ret0, _ := ret[0].(*iaasalpha.RoutingTableListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoutingTablesOfAreaExecute indicates an expected call of ListRoutingTablesOfAreaExecute.
func (mr *MockDefaultApiMockRecorder) ListRoutingTablesOfAreaExecute(ctx, organizationId, areaId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutingTablesOfAreaExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListRoutingTablesOfAreaExecute), ctx, organizationId, areaId, region)
}

// PartialUpdateNetwork mocks base method.
func (m *MockDefaultApi) PartialUpdateNetwork(ctx context.Context, projectId, region, networkId string) iaasalpha.ApiPartialUpdateNetworkRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateNetwork", ctx, projectId, region, networkId)
	ret0, _ := ret[0].(iaasalpha.ApiPartialUpdateNetworkRequest)
	return ret0
}

// PartialUpdateNetwork indicates an expected call of PartialUpdateNetwork.
func (mr *MockDefaultApiMockRecorder) PartialUpdateNetwork(ctx, projectId, region, networkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateNetwork", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateNetwork), ctx, projectId, region, networkId)
}

// PartialUpdateNetworkExecute mocks base method.
func (m *MockDefaultApi) PartialUpdateNetworkExecute(ctx context.Context, projectId, region, networkId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateNetworkExecute", ctx, projectId, region, networkId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PartialUpdateNetworkExecute indicates an expected call of PartialUpdateNetworkExecute.
func (mr *MockDefaultApiMockRecorder) PartialUpdateNetworkExecute(ctx, projectId, region, networkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateNetworkExecute", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateNetworkExecute), ctx, projectId, region, networkId)
}

// UpdateRouteOfRoutingTable mocks base method.
func (m *MockDefaultApi) UpdateRouteOfRoutingTable(ctx context.Context, organizationId, areaId, region, routingTableId, routeId string) iaasalpha.ApiUpdateRouteOfRoutingTableRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRouteOfRoutingTable", ctx, organizationId, areaId, region, routingTableId, routeId)
	ret0, _ := ret[0].(iaasalpha.ApiUpdateRouteOfRoutingTableRequest)
	return ret0
}

// UpdateRouteOfRoutingTable indicates an expected call of UpdateRouteOfRoutingTable.
func (mr *MockDefaultApiMockRecorder) UpdateRouteOfRoutingTable(ctx, organizationId, areaId, region, routingTableId, routeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRouteOfRoutingTable", reflect.TypeOf((*MockDefaultApi)(nil).UpdateRouteOfRoutingTable), ctx, organizationId, areaId, region, routingTableId, routeId)
}

// UpdateRouteOfRoutingTableExecute mocks base method.
func (m *MockDefaultApi) UpdateRouteOfRoutingTableExecute(ctx context.Context, organizationId, areaId, region, routingTableId, routeId string) (*iaasalpha.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRouteOfRoutingTableExecute", ctx, organizationId, areaId, region, routingTableId, routeId)
	ret0, _ := ret[0].(*iaasalpha.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRouteOfRoutingTableExecute indicates an expected call of UpdateRouteOfRoutingTableExecute.
func (mr *MockDefaultApiMockRecorder) UpdateRouteOfRoutingTableExecute(ctx, organizationId, areaId, region, routingTableId, routeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRouteOfRoutingTableExecute", reflect.TypeOf((*MockDefaultApi)(nil).UpdateRouteOfRoutingTableExecute), ctx, organizationId, areaId, region, routingTableId, routeId)
}

// UpdateRoutingTableOfArea mocks base method.
func (m *MockDefaultApi) UpdateRoutingTableOfArea(ctx context.Context, organizationId, areaId, region, routingTableId string) iaasalpha.ApiUpdateRoutingTableOfAreaRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoutingTableOfArea", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(iaasalpha.ApiUpdateRoutingTableOfAreaRequest)
	return ret0
}

// UpdateRoutingTableOfArea indicates an expected call of UpdateRoutingTableOfArea.
func (mr *MockDefaultApiMockRecorder) UpdateRoutingTableOfArea(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoutingTableOfArea", reflect.TypeOf((*MockDefaultApi)(nil).UpdateRoutingTableOfArea), ctx, organizationId, areaId, region, routingTableId)
}

// UpdateRoutingTableOfAreaExecute mocks base method.
func (m *MockDefaultApi) UpdateRoutingTableOfAreaExecute(ctx context.Context, organizationId, areaId, region, routingTableId string) (*iaasalpha.RoutingTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoutingTableOfAreaExecute", ctx, organizationId, areaId, region, routingTableId)
	ret0, _ := ret[0].(*iaasalpha.RoutingTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoutingTableOfAreaExecute indicates an expected call of UpdateRoutingTableOfAreaExecute.
func (mr *MockDefaultApiMockRecorder) UpdateRoutingTableOfAreaExecute(ctx, organizationId, areaId, region, routingTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoutingTableOfAreaExecute", reflect.TypeOf((*MockDefaultApi)(nil).UpdateRoutingTableOfAreaExecute), ctx, organizationId, areaId, region, routingTableId)
}
