// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/iaasalpha (interfaces: ApiCreateNetworkRequest,ApiGetNetworkRequest,ApiPartialUpdateNetworkRequest,ApiDeleteNetworkRequest)
//
// Generated by this command:
//
//	mockgen -destination=./mock/v2/requests.go -package=mock_network_v2 github.com/stackitcloud/stackit-sdk-go/services/iaasalpha ApiCreateNetworkRequest,ApiGetNetworkRequest,ApiPartialUpdateNetworkRequest,ApiDeleteNetworkRequest
//

// Package mock_network_v2 is a generated GoMock package.
package mock_network_v2

import (
	reflect "reflect"

	iaasalpha "github.com/stackitcloud/stackit-sdk-go/services/iaasalpha"
	gomock "go.uber.org/mock/gomock"
)

// MockApiCreateNetworkRequest is a mock of ApiCreateNetworkRequest interface.
type MockApiCreateNetworkRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiCreateNetworkRequestMockRecorder
	isgomock struct{}
}

// MockApiCreateNetworkRequestMockRecorder is the mock recorder for MockApiCreateNetworkRequest.
type MockApiCreateNetworkRequestMockRecorder struct {
	mock *MockApiCreateNetworkRequest
}

// NewMockApiCreateNetworkRequest creates a new mock instance.
func NewMockApiCreateNetworkRequest(ctrl *gomock.Controller) *MockApiCreateNetworkRequest {
	mock := &MockApiCreateNetworkRequest{ctrl: ctrl}
	mock.recorder = &MockApiCreateNetworkRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiCreateNetworkRequest) EXPECT() *MockApiCreateNetworkRequestMockRecorder {
	return m.recorder
}

// CreateNetworkPayload mocks base method.
func (m *MockApiCreateNetworkRequest) CreateNetworkPayload(createNetworkPayload iaasalpha.CreateNetworkPayload) iaasalpha.ApiCreateNetworkRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetworkPayload", createNetworkPayload)
	ret0, _ := ret[0].(iaasalpha.ApiCreateNetworkRequest)
	return ret0
}

// CreateNetworkPayload indicates an expected call of CreateNetworkPayload.
func (mr *MockApiCreateNetworkRequestMockRecorder) CreateNetworkPayload(createNetworkPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetworkPayload", reflect.TypeOf((*MockApiCreateNetworkRequest)(nil).CreateNetworkPayload), createNetworkPayload)
}

// Execute mocks base method.
func (m *MockApiCreateNetworkRequest) Execute() (*iaasalpha.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*iaasalpha.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiCreateNetworkRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiCreateNetworkRequest)(nil).Execute))
}

// MockApiGetNetworkRequest is a mock of ApiGetNetworkRequest interface.
type MockApiGetNetworkRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiGetNetworkRequestMockRecorder
	isgomock struct{}
}

// MockApiGetNetworkRequestMockRecorder is the mock recorder for MockApiGetNetworkRequest.
type MockApiGetNetworkRequestMockRecorder struct {
	mock *MockApiGetNetworkRequest
}

// NewMockApiGetNetworkRequest creates a new mock instance.
func NewMockApiGetNetworkRequest(ctrl *gomock.Controller) *MockApiGetNetworkRequest {
	mock := &MockApiGetNetworkRequest{ctrl: ctrl}
	mock.recorder = &MockApiGetNetworkRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiGetNetworkRequest) EXPECT() *MockApiGetNetworkRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiGetNetworkRequest) Execute() (*iaasalpha.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*iaasalpha.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiGetNetworkRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiGetNetworkRequest)(nil).Execute))
}

// MockApiPartialUpdateNetworkRequest is a mock of ApiPartialUpdateNetworkRequest interface.
type MockApiPartialUpdateNetworkRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiPartialUpdateNetworkRequestMockRecorder
	isgomock struct{}
}

// MockApiPartialUpdateNetworkRequestMockRecorder is the mock recorder for MockApiPartialUpdateNetworkRequest.
type MockApiPartialUpdateNetworkRequestMockRecorder struct {
	mock *MockApiPartialUpdateNetworkRequest
}

// NewMockApiPartialUpdateNetworkRequest creates a new mock instance.
func NewMockApiPartialUpdateNetworkRequest(ctrl *gomock.Controller) *MockApiPartialUpdateNetworkRequest {
	mock := &MockApiPartialUpdateNetworkRequest{ctrl: ctrl}
	mock.recorder = &MockApiPartialUpdateNetworkRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiPartialUpdateNetworkRequest) EXPECT() *MockApiPartialUpdateNetworkRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiPartialUpdateNetworkRequest) Execute() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockApiPartialUpdateNetworkRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiPartialUpdateNetworkRequest)(nil).Execute))
}

// PartialUpdateNetworkPayload mocks base method.
func (m *MockApiPartialUpdateNetworkRequest) PartialUpdateNetworkPayload(partialUpdateNetworkPayload iaasalpha.PartialUpdateNetworkPayload) iaasalpha.ApiPartialUpdateNetworkRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateNetworkPayload", partialUpdateNetworkPayload)
	ret0, _ := ret[0].(iaasalpha.ApiPartialUpdateNetworkRequest)
	return ret0
}

// PartialUpdateNetworkPayload indicates an expected call of PartialUpdateNetworkPayload.
func (mr *MockApiPartialUpdateNetworkRequestMockRecorder) PartialUpdateNetworkPayload(partialUpdateNetworkPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateNetworkPayload", reflect.TypeOf((*MockApiPartialUpdateNetworkRequest)(nil).PartialUpdateNetworkPayload), partialUpdateNetworkPayload)
}

// MockApiDeleteNetworkRequest is a mock of ApiDeleteNetworkRequest interface.
type MockApiDeleteNetworkRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiDeleteNetworkRequestMockRecorder
	isgomock struct{}
}

// MockApiDeleteNetworkRequestMockRecorder is the mock recorder for MockApiDeleteNetworkRequest.
type MockApiDeleteNetworkRequestMockRecorder struct {
	mock *MockApiDeleteNetworkRequest
}

// NewMockApiDeleteNetworkRequest creates a new mock instance.
func NewMockApiDeleteNetworkRequest(ctrl *gomock.Controller) *MockApiDeleteNetworkRequest {
	mock := &MockApiDeleteNetworkRequest{ctrl: ctrl}
	mock.recorder = &MockApiDeleteNetworkRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiDeleteNetworkRequest) EXPECT() *MockApiDeleteNetworkRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiDeleteNetworkRequest) Execute() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockApiDeleteNetworkRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiDeleteNetworkRequest)(nil).Execute))
}
