// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/mariadb (interfaces: DefaultApi)
//
// Generated by this command:
//
//	mockgen -destination=./mock/instance.go -package=mock_instance github.com/stackitcloud/stackit-sdk-go/services/mariadb DefaultApi
//

// Package mock_instance is a generated GoMock package.
package mock_instance

import (
	context "context"
	os "os"
	reflect "reflect"

	mariadb "github.com/stackitcloud/stackit-sdk-go/services/mariadb"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultApi is a mock of DefaultApi interface.
type MockDefaultApi struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultApiMockRecorder
	isgomock struct{}
}

// MockDefaultApiMockRecorder is the mock recorder for MockDefaultApi.
type MockDefaultApiMockRecorder struct {
	mock *MockDefaultApi
}

// NewMockDefaultApi creates a new mock instance.
func NewMockDefaultApi(ctrl *gomock.Controller) *MockDefaultApi {
	mock := &MockDefaultApi{ctrl: ctrl}
	mock.recorder = &MockDefaultApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultApi) EXPECT() *MockDefaultApiMockRecorder {
	return m.recorder
}

// CreateBackup mocks base method.
func (m *MockDefaultApi) CreateBackup(ctx context.Context, instanceId, projectId string) mariadb.ApiCreateBackupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackup", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiCreateBackupRequest)
	return ret0
}

// CreateBackup indicates an expected call of CreateBackup.
func (mr *MockDefaultApiMockRecorder) CreateBackup(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackup", reflect.TypeOf((*MockDefaultApi)(nil).CreateBackup), ctx, instanceId, projectId)
}

// CreateBackupExecute mocks base method.
func (m *MockDefaultApi) CreateBackupExecute(ctx context.Context, instanceId, projectId string) ([]mariadb.CreateBackupResponseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackupExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].([]mariadb.CreateBackupResponseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBackupExecute indicates an expected call of CreateBackupExecute.
func (mr *MockDefaultApiMockRecorder) CreateBackupExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackupExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateBackupExecute), ctx, instanceId, projectId)
}

// CreateCredentials mocks base method.
func (m *MockDefaultApi) CreateCredentials(ctx context.Context, projectId, instanceId string) mariadb.ApiCreateCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredentials", ctx, projectId, instanceId)
	ret0, _ := ret[0].(mariadb.ApiCreateCredentialsRequest)
	return ret0
}

// CreateCredentials indicates an expected call of CreateCredentials.
func (mr *MockDefaultApiMockRecorder) CreateCredentials(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredentials", reflect.TypeOf((*MockDefaultApi)(nil).CreateCredentials), ctx, projectId, instanceId)
}

// CreateCredentialsExecute mocks base method.
func (m *MockDefaultApi) CreateCredentialsExecute(ctx context.Context, projectId, instanceId string) (*mariadb.CredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredentialsExecute", ctx, projectId, instanceId)
	ret0, _ := ret[0].(*mariadb.CredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredentialsExecute indicates an expected call of CreateCredentialsExecute.
func (mr *MockDefaultApiMockRecorder) CreateCredentialsExecute(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredentialsExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateCredentialsExecute), ctx, projectId, instanceId)
}

// CreateInstance mocks base method.
func (m *MockDefaultApi) CreateInstance(ctx context.Context, projectId string) mariadb.ApiCreateInstanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, projectId)
	ret0, _ := ret[0].(mariadb.ApiCreateInstanceRequest)
	return ret0
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockDefaultApiMockRecorder) CreateInstance(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockDefaultApi)(nil).CreateInstance), ctx, projectId)
}

// CreateInstanceExecute mocks base method.
func (m *MockDefaultApi) CreateInstanceExecute(ctx context.Context, projectId string) (*mariadb.CreateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstanceExecute", ctx, projectId)
	ret0, _ := ret[0].(*mariadb.CreateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstanceExecute indicates an expected call of CreateInstanceExecute.
func (mr *MockDefaultApiMockRecorder) CreateInstanceExecute(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateInstanceExecute), ctx, projectId)
}

// DeleteCredentials mocks base method.
func (m *MockDefaultApi) DeleteCredentials(ctx context.Context, projectId, instanceId, credentialsId string) mariadb.ApiDeleteCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentials", ctx, projectId, instanceId, credentialsId)
	ret0, _ := ret[0].(mariadb.ApiDeleteCredentialsRequest)
	return ret0
}

// DeleteCredentials indicates an expected call of DeleteCredentials.
func (mr *MockDefaultApiMockRecorder) DeleteCredentials(ctx, projectId, instanceId, credentialsId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentials", reflect.TypeOf((*MockDefaultApi)(nil).DeleteCredentials), ctx, projectId, instanceId, credentialsId)
}

// DeleteCredentialsExecute mocks base method.
func (m *MockDefaultApi) DeleteCredentialsExecute(ctx context.Context, projectId, instanceId, credentialsId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentialsExecute", ctx, projectId, instanceId, credentialsId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredentialsExecute indicates an expected call of DeleteCredentialsExecute.
func (mr *MockDefaultApiMockRecorder) DeleteCredentialsExecute(ctx, projectId, instanceId, credentialsId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentialsExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteCredentialsExecute), ctx, projectId, instanceId, credentialsId)
}

// DeleteInstance mocks base method.
func (m *MockDefaultApi) DeleteInstance(ctx context.Context, projectId, instanceId string) mariadb.ApiDeleteInstanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, projectId, instanceId)
	ret0, _ := ret[0].(mariadb.ApiDeleteInstanceRequest)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockDefaultApiMockRecorder) DeleteInstance(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockDefaultApi)(nil).DeleteInstance), ctx, projectId, instanceId)
}

// DeleteInstanceExecute mocks base method.
func (m *MockDefaultApi) DeleteInstanceExecute(ctx context.Context, projectId, instanceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstanceExecute", ctx, projectId, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstanceExecute indicates an expected call of DeleteInstanceExecute.
func (mr *MockDefaultApiMockRecorder) DeleteInstanceExecute(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteInstanceExecute), ctx, projectId, instanceId)
}

// DownloadBackup mocks base method.
func (m *MockDefaultApi) DownloadBackup(ctx context.Context, backupId int32, instanceId, projectId string) mariadb.ApiDownloadBackupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadBackup", ctx, backupId, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiDownloadBackupRequest)
	return ret0
}

// DownloadBackup indicates an expected call of DownloadBackup.
func (mr *MockDefaultApiMockRecorder) DownloadBackup(ctx, backupId, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBackup", reflect.TypeOf((*MockDefaultApi)(nil).DownloadBackup), ctx, backupId, instanceId, projectId)
}

// DownloadBackupExecute mocks base method.
func (m *MockDefaultApi) DownloadBackupExecute(ctx context.Context, backupId int32, instanceId, projectId string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadBackupExecute", ctx, backupId, instanceId, projectId)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadBackupExecute indicates an expected call of DownloadBackupExecute.
func (mr *MockDefaultApiMockRecorder) DownloadBackupExecute(ctx, backupId, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBackupExecute", reflect.TypeOf((*MockDefaultApi)(nil).DownloadBackupExecute), ctx, backupId, instanceId, projectId)
}

// GetCredentials mocks base method.
func (m *MockDefaultApi) GetCredentials(ctx context.Context, projectId, instanceId, credentialsId string) mariadb.ApiGetCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, projectId, instanceId, credentialsId)
	ret0, _ := ret[0].(mariadb.ApiGetCredentialsRequest)
	return ret0
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockDefaultApiMockRecorder) GetCredentials(ctx, projectId, instanceId, credentialsId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockDefaultApi)(nil).GetCredentials), ctx, projectId, instanceId, credentialsId)
}

// GetCredentialsExecute mocks base method.
func (m *MockDefaultApi) GetCredentialsExecute(ctx context.Context, projectId, instanceId, credentialsId string) (*mariadb.CredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsExecute", ctx, projectId, instanceId, credentialsId)
	ret0, _ := ret[0].(*mariadb.CredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialsExecute indicates an expected call of GetCredentialsExecute.
func (mr *MockDefaultApiMockRecorder) GetCredentialsExecute(ctx, projectId, instanceId, credentialsId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetCredentialsExecute), ctx, projectId, instanceId, credentialsId)
}

// GetInstance mocks base method.
func (m *MockDefaultApi) GetInstance(ctx context.Context, projectId, instanceId string) mariadb.ApiGetInstanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, projectId, instanceId)
	ret0, _ := ret[0].(mariadb.ApiGetInstanceRequest)
	return ret0
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockDefaultApiMockRecorder) GetInstance(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockDefaultApi)(nil).GetInstance), ctx, projectId, instanceId)
}

// GetInstanceExecute mocks base method.
func (m *MockDefaultApi) GetInstanceExecute(ctx context.Context, projectId, instanceId string) (*mariadb.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceExecute", ctx, projectId, instanceId)
	ret0, _ := ret[0].(*mariadb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceExecute indicates an expected call of GetInstanceExecute.
func (mr *MockDefaultApiMockRecorder) GetInstanceExecute(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetInstanceExecute), ctx, projectId, instanceId)
}

// GetMetrics mocks base method.
func (m *MockDefaultApi) GetMetrics(ctx context.Context, instanceId, projectId string) mariadb.ApiGetMetricsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiGetMetricsRequest)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockDefaultApiMockRecorder) GetMetrics(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockDefaultApi)(nil).GetMetrics), ctx, instanceId, projectId)
}

// GetMetricsExecute mocks base method.
func (m *MockDefaultApi) GetMetricsExecute(ctx context.Context, instanceId, projectId string) (*mariadb.GetMetricsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].(*mariadb.GetMetricsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsExecute indicates an expected call of GetMetricsExecute.
func (mr *MockDefaultApiMockRecorder) GetMetricsExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetMetricsExecute), ctx, instanceId, projectId)
}

// ListBackups mocks base method.
func (m *MockDefaultApi) ListBackups(ctx context.Context, instanceId, projectId string) mariadb.ApiListBackupsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackups", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiListBackupsRequest)
	return ret0
}

// ListBackups indicates an expected call of ListBackups.
func (mr *MockDefaultApiMockRecorder) ListBackups(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackups", reflect.TypeOf((*MockDefaultApi)(nil).ListBackups), ctx, instanceId, projectId)
}

// ListBackupsExecute mocks base method.
func (m *MockDefaultApi) ListBackupsExecute(ctx context.Context, instanceId, projectId string) (*mariadb.ListBackupsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackupsExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].(*mariadb.ListBackupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackupsExecute indicates an expected call of ListBackupsExecute.
func (mr *MockDefaultApiMockRecorder) ListBackupsExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackupsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListBackupsExecute), ctx, instanceId, projectId)
}

// ListCredentials mocks base method.
func (m *MockDefaultApi) ListCredentials(ctx context.Context, projectId, instanceId string) mariadb.ApiListCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx, projectId, instanceId)
	ret0, _ := ret[0].(mariadb.ApiListCredentialsRequest)
	return ret0
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockDefaultApiMockRecorder) ListCredentials(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockDefaultApi)(nil).ListCredentials), ctx, projectId, instanceId)
}

// ListCredentialsExecute mocks base method.
func (m *MockDefaultApi) ListCredentialsExecute(ctx context.Context, projectId, instanceId string) (*mariadb.ListCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentialsExecute", ctx, projectId, instanceId)
	ret0, _ := ret[0].(*mariadb.ListCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentialsExecute indicates an expected call of ListCredentialsExecute.
func (mr *MockDefaultApiMockRecorder) ListCredentialsExecute(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentialsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListCredentialsExecute), ctx, projectId, instanceId)
}

// ListInstances mocks base method.
func (m *MockDefaultApi) ListInstances(ctx context.Context, projectId string) mariadb.ApiListInstancesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, projectId)
	ret0, _ := ret[0].(mariadb.ApiListInstancesRequest)
	return ret0
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockDefaultApiMockRecorder) ListInstances(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockDefaultApi)(nil).ListInstances), ctx, projectId)
}

// ListInstancesExecute mocks base method.
func (m *MockDefaultApi) ListInstancesExecute(ctx context.Context, projectId string) (*mariadb.ListInstancesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstancesExecute", ctx, projectId)
	ret0, _ := ret[0].(*mariadb.ListInstancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstancesExecute indicates an expected call of ListInstancesExecute.
func (mr *MockDefaultApiMockRecorder) ListInstancesExecute(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstancesExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListInstancesExecute), ctx, projectId)
}

// ListOfferings mocks base method.
func (m *MockDefaultApi) ListOfferings(ctx context.Context, projectId string) mariadb.ApiListOfferingsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOfferings", ctx, projectId)
	ret0, _ := ret[0].(mariadb.ApiListOfferingsRequest)
	return ret0
}

// ListOfferings indicates an expected call of ListOfferings.
func (mr *MockDefaultApiMockRecorder) ListOfferings(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOfferings", reflect.TypeOf((*MockDefaultApi)(nil).ListOfferings), ctx, projectId)
}

// ListOfferingsExecute mocks base method.
func (m *MockDefaultApi) ListOfferingsExecute(ctx context.Context, projectId string) (*mariadb.ListOfferingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOfferingsExecute", ctx, projectId)
	ret0, _ := ret[0].(*mariadb.ListOfferingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOfferingsExecute indicates an expected call of ListOfferingsExecute.
func (mr *MockDefaultApiMockRecorder) ListOfferingsExecute(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOfferingsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListOfferingsExecute), ctx, projectId)
}

// ListRestores mocks base method.
func (m *MockDefaultApi) ListRestores(ctx context.Context, instanceId, projectId string) mariadb.ApiListRestoresRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRestores", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiListRestoresRequest)
	return ret0
}

// ListRestores indicates an expected call of ListRestores.
func (mr *MockDefaultApiMockRecorder) ListRestores(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRestores", reflect.TypeOf((*MockDefaultApi)(nil).ListRestores), ctx, instanceId, projectId)
}

// ListRestoresExecute mocks base method.
func (m *MockDefaultApi) ListRestoresExecute(ctx context.Context, instanceId, projectId string) (*mariadb.ListRestoresResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRestoresExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].(*mariadb.ListRestoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRestoresExecute indicates an expected call of ListRestoresExecute.
func (mr *MockDefaultApiMockRecorder) ListRestoresExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRestoresExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListRestoresExecute), ctx, instanceId, projectId)
}

// PartialUpdateInstance mocks base method.
func (m *MockDefaultApi) PartialUpdateInstance(ctx context.Context, projectId, instanceId string) mariadb.ApiPartialUpdateInstanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateInstance", ctx, projectId, instanceId)
	ret0, _ := ret[0].(mariadb.ApiPartialUpdateInstanceRequest)
	return ret0
}

// PartialUpdateInstance indicates an expected call of PartialUpdateInstance.
func (mr *MockDefaultApiMockRecorder) PartialUpdateInstance(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateInstance", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateInstance), ctx, projectId, instanceId)
}

// PartialUpdateInstanceExecute mocks base method.
func (m *MockDefaultApi) PartialUpdateInstanceExecute(ctx context.Context, projectId, instanceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateInstanceExecute", ctx, projectId, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PartialUpdateInstanceExecute indicates an expected call of PartialUpdateInstanceExecute.
func (mr *MockDefaultApiMockRecorder) PartialUpdateInstanceExecute(ctx, projectId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateInstanceExecute", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateInstanceExecute), ctx, projectId, instanceId)
}

// TriggerRecreate mocks base method.
func (m *MockDefaultApi) TriggerRecreate(ctx context.Context, instanceId, projectId string) mariadb.ApiTriggerRecreateRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerRecreate", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiTriggerRecreateRequest)
	return ret0
}

// TriggerRecreate indicates an expected call of TriggerRecreate.
func (mr *MockDefaultApiMockRecorder) TriggerRecreate(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerRecreate", reflect.TypeOf((*MockDefaultApi)(nil).TriggerRecreate), ctx, instanceId, projectId)
}

// TriggerRecreateExecute mocks base method.
func (m *MockDefaultApi) TriggerRecreateExecute(ctx context.Context, instanceId, projectId string) (*mariadb.CreateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerRecreateExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].(*mariadb.CreateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerRecreateExecute indicates an expected call of TriggerRecreateExecute.
func (mr *MockDefaultApiMockRecorder) TriggerRecreateExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerRecreateExecute", reflect.TypeOf((*MockDefaultApi)(nil).TriggerRecreateExecute), ctx, instanceId, projectId)
}

// TriggerRestart mocks base method.
func (m *MockDefaultApi) TriggerRestart(ctx context.Context, instanceId, projectId string) mariadb.ApiTriggerRestartRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerRestart", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiTriggerRestartRequest)
	return ret0
}

// TriggerRestart indicates an expected call of TriggerRestart.
func (mr *MockDefaultApiMockRecorder) TriggerRestart(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerRestart", reflect.TypeOf((*MockDefaultApi)(nil).TriggerRestart), ctx, instanceId, projectId)
}

// TriggerRestartExecute mocks base method.
func (m *MockDefaultApi) TriggerRestartExecute(ctx context.Context, instanceId, projectId string) (*mariadb.CreateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerRestartExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].(*mariadb.CreateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerRestartExecute indicates an expected call of TriggerRestartExecute.
func (mr *MockDefaultApiMockRecorder) TriggerRestartExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerRestartExecute", reflect.TypeOf((*MockDefaultApi)(nil).TriggerRestartExecute), ctx, instanceId, projectId)
}

// TriggerRestore mocks base method.
func (m *MockDefaultApi) TriggerRestore(ctx context.Context, instanceId, projectId string, backupId int32) mariadb.ApiTriggerRestoreRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerRestore", ctx, instanceId, projectId, backupId)
	ret0, _ := ret[0].(mariadb.ApiTriggerRestoreRequest)
	return ret0
}

// TriggerRestore indicates an expected call of TriggerRestore.
func (mr *MockDefaultApiMockRecorder) TriggerRestore(ctx, instanceId, projectId, backupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerRestore", reflect.TypeOf((*MockDefaultApi)(nil).TriggerRestore), ctx, instanceId, projectId, backupId)
}

// TriggerRestoreExecute mocks base method.
func (m *MockDefaultApi) TriggerRestoreExecute(ctx context.Context, instanceId, projectId string, backupId int32) (*mariadb.TriggerRestoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerRestoreExecute", ctx, instanceId, projectId, backupId)
	ret0, _ := ret[0].(*mariadb.TriggerRestoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerRestoreExecute indicates an expected call of TriggerRestoreExecute.
func (mr *MockDefaultApiMockRecorder) TriggerRestoreExecute(ctx, instanceId, projectId, backupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerRestoreExecute", reflect.TypeOf((*MockDefaultApi)(nil).TriggerRestoreExecute), ctx, instanceId, projectId, backupId)
}

// UpdateBackupsConfig mocks base method.
func (m *MockDefaultApi) UpdateBackupsConfig(ctx context.Context, instanceId, projectId string) mariadb.ApiUpdateBackupsConfigRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackupsConfig", ctx, instanceId, projectId)
	ret0, _ := ret[0].(mariadb.ApiUpdateBackupsConfigRequest)
	return ret0
}

// UpdateBackupsConfig indicates an expected call of UpdateBackupsConfig.
func (mr *MockDefaultApiMockRecorder) UpdateBackupsConfig(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackupsConfig", reflect.TypeOf((*MockDefaultApi)(nil).UpdateBackupsConfig), ctx, instanceId, projectId)
}

// UpdateBackupsConfigExecute mocks base method.
func (m *MockDefaultApi) UpdateBackupsConfigExecute(ctx context.Context, instanceId, projectId string) (*mariadb.UpdateBackupsConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackupsConfigExecute", ctx, instanceId, projectId)
	ret0, _ := ret[0].(*mariadb.UpdateBackupsConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBackupsConfigExecute indicates an expected call of UpdateBackupsConfigExecute.
func (mr *MockDefaultApiMockRecorder) UpdateBackupsConfigExecute(ctx, instanceId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackupsConfigExecute", reflect.TypeOf((*MockDefaultApi)(nil).UpdateBackupsConfigExecute), ctx, instanceId, projectId)
}
