// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/mariadb (interfaces: ApiListOfferingsRequest,ApiCreateInstanceRequest,ApiGetInstanceRequest,ApiPartialUpdateInstanceRequest,ApiDeleteInstanceRequest)
//
// Generated by this command:
//
//	mockgen -destination=./mock/requests.go -package=mock_instance github.com/stackitcloud/stackit-sdk-go/services/mariadb ApiListOfferingsRequest,ApiCreateInstanceRequest,ApiGetInstanceRequest,ApiPartialUpdateInstanceRequest,ApiDeleteInstanceRequest
//

// Package mock_instance is a generated GoMock package.
package mock_instance

import (
	reflect "reflect"

	mariadb "github.com/stackitcloud/stackit-sdk-go/services/mariadb"
	gomock "go.uber.org/mock/gomock"
)

// MockApiListOfferingsRequest is a mock of ApiListOfferingsRequest interface.
type MockApiListOfferingsRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiListOfferingsRequestMockRecorder
	isgomock struct{}
}

// MockApiListOfferingsRequestMockRecorder is the mock recorder for MockApiListOfferingsRequest.
type MockApiListOfferingsRequestMockRecorder struct {
	mock *MockApiListOfferingsRequest
}

// NewMockApiListOfferingsRequest creates a new mock instance.
func NewMockApiListOfferingsRequest(ctrl *gomock.Controller) *MockApiListOfferingsRequest {
	mock := &MockApiListOfferingsRequest{ctrl: ctrl}
	mock.recorder = &MockApiListOfferingsRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiListOfferingsRequest) EXPECT() *MockApiListOfferingsRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiListOfferingsRequest) Execute() (*mariadb.ListOfferingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*mariadb.ListOfferingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiListOfferingsRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiListOfferingsRequest)(nil).Execute))
}

// MockApiCreateInstanceRequest is a mock of ApiCreateInstanceRequest interface.
type MockApiCreateInstanceRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiCreateInstanceRequestMockRecorder
	isgomock struct{}
}

// MockApiCreateInstanceRequestMockRecorder is the mock recorder for MockApiCreateInstanceRequest.
type MockApiCreateInstanceRequestMockRecorder struct {
	mock *MockApiCreateInstanceRequest
}

// NewMockApiCreateInstanceRequest creates a new mock instance.
func NewMockApiCreateInstanceRequest(ctrl *gomock.Controller) *MockApiCreateInstanceRequest {
	mock := &MockApiCreateInstanceRequest{ctrl: ctrl}
	mock.recorder = &MockApiCreateInstanceRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiCreateInstanceRequest) EXPECT() *MockApiCreateInstanceRequestMockRecorder {
	return m.recorder
}

// CreateInstancePayload mocks base method.
func (m *MockApiCreateInstanceRequest) CreateInstancePayload(createInstancePayload mariadb.CreateInstancePayload) mariadb.ApiCreateInstanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstancePayload", createInstancePayload)
	ret0, _ := ret[0].(mariadb.ApiCreateInstanceRequest)
	return ret0
}

// CreateInstancePayload indicates an expected call of CreateInstancePayload.
func (mr *MockApiCreateInstanceRequestMockRecorder) CreateInstancePayload(createInstancePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstancePayload", reflect.TypeOf((*MockApiCreateInstanceRequest)(nil).CreateInstancePayload), createInstancePayload)
}

// Execute mocks base method.
func (m *MockApiCreateInstanceRequest) Execute() (*mariadb.CreateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*mariadb.CreateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiCreateInstanceRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiCreateInstanceRequest)(nil).Execute))
}

// MockApiGetInstanceRequest is a mock of ApiGetInstanceRequest interface.
type MockApiGetInstanceRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiGetInstanceRequestMockRecorder
	isgomock struct{}
}

// MockApiGetInstanceRequestMockRecorder is the mock recorder for MockApiGetInstanceRequest.
type MockApiGetInstanceRequestMockRecorder struct {
	mock *MockApiGetInstanceRequest
}

// NewMockApiGetInstanceRequest creates a new mock instance.
func NewMockApiGetInstanceRequest(ctrl *gomock.Controller) *MockApiGetInstanceRequest {
	mock := &MockApiGetInstanceRequest{ctrl: ctrl}
	mock.recorder = &MockApiGetInstanceRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiGetInstanceRequest) EXPECT() *MockApiGetInstanceRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiGetInstanceRequest) Execute() (*mariadb.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*mariadb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiGetInstanceRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiGetInstanceRequest)(nil).Execute))
}

// MockApiPartialUpdateInstanceRequest is a mock of ApiPartialUpdateInstanceRequest interface.
type MockApiPartialUpdateInstanceRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiPartialUpdateInstanceRequestMockRecorder
	isgomock struct{}
}

// MockApiPartialUpdateInstanceRequestMockRecorder is the mock recorder for MockApiPartialUpdateInstanceRequest.
type MockApiPartialUpdateInstanceRequestMockRecorder struct {
	mock *MockApiPartialUpdateInstanceRequest
}

// NewMockApiPartialUpdateInstanceRequest creates a new mock instance.
func NewMockApiPartialUpdateInstanceRequest(ctrl *gomock.Controller) *MockApiPartialUpdateInstanceRequest {
	mock := &MockApiPartialUpdateInstanceRequest{ctrl: ctrl}
	mock.recorder = &MockApiPartialUpdateInstanceRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiPartialUpdateInstanceRequest) EXPECT() *MockApiPartialUpdateInstanceRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiPartialUpdateInstanceRequest) Execute() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockApiPartialUpdateInstanceRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiPartialUpdateInstanceRequest)(nil).Execute))
}

// PartialUpdateInstancePayload mocks base method.
func (m *MockApiPartialUpdateInstanceRequest) PartialUpdateInstancePayload(partialUpdateInstancePayload mariadb.PartialUpdateInstancePayload) mariadb.ApiPartialUpdateInstanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateInstancePayload", partialUpdateInstancePayload)
	ret0, _ := ret[0].(mariadb.ApiPartialUpdateInstanceRequest)
	return ret0
}

// PartialUpdateInstancePayload indicates an expected call of PartialUpdateInstancePayload.
func (mr *MockApiPartialUpdateInstanceRequestMockRecorder) PartialUpdateInstancePayload(partialUpdateInstancePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateInstancePayload", reflect.TypeOf((*MockApiPartialUpdateInstanceRequest)(nil).PartialUpdateInstancePayload), partialUpdateInstancePayload)
}

// MockApiDeleteInstanceRequest is a mock of ApiDeleteInstanceRequest interface.
type MockApiDeleteInstanceRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiDeleteInstanceRequestMockRecorder
	isgomock struct{}
}

// MockApiDeleteInstanceRequestMockRecorder is the mock recorder for MockApiDeleteInstanceRequest.
type MockApiDeleteInstanceRequestMockRecorder struct {
	mock *MockApiDeleteInstanceRequest
}

// NewMockApiDeleteInstanceRequest creates a new mock instance.
func NewMockApiDeleteInstanceRequest(ctrl *gomock.Controller) *MockApiDeleteInstanceRequest {
	mock := &MockApiDeleteInstanceRequest{ctrl: ctrl}
	mock.recorder = &MockApiDeleteInstanceRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiDeleteInstanceRequest) EXPECT() *MockApiDeleteInstanceRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiDeleteInstanceRequest) Execute() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockApiDeleteInstanceRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiDeleteInstanceRequest)(nil).Execute))
}
