// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/dns (interfaces: ApiCreateRecordSetRequest,ApiGetRecordSetRequest,ApiPartialUpdateRecordSetRequest,ApiDeleteRecordSetRequest,ApiGetZoneRequest)
//
// Generated by this command:
//
//	mockgen -destination=./mock/requests.go -package=mock_recordset github.com/stackitcloud/stackit-sdk-go/services/dns ApiCreateRecordSetRequest,ApiGetRecordSetRequest,ApiPartialUpdateRecordSetRequest,ApiDeleteRecordSetRequest,ApiGetZoneRequest
//

// Package mock_recordset is a generated GoMock package.
package mock_recordset

import (
	reflect "reflect"

	dns "github.com/stackitcloud/stackit-sdk-go/services/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockApiCreateRecordSetRequest is a mock of ApiCreateRecordSetRequest interface.
type MockApiCreateRecordSetRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiCreateRecordSetRequestMockRecorder
	isgomock struct{}
}

// MockApiCreateRecordSetRequestMockRecorder is the mock recorder for MockApiCreateRecordSetRequest.
type MockApiCreateRecordSetRequestMockRecorder struct {
	mock *MockApiCreateRecordSetRequest
}

// NewMockApiCreateRecordSetRequest creates a new mock instance.
func NewMockApiCreateRecordSetRequest(ctrl *gomock.Controller) *MockApiCreateRecordSetRequest {
	mock := &MockApiCreateRecordSetRequest{ctrl: ctrl}
	mock.recorder = &MockApiCreateRecordSetRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiCreateRecordSetRequest) EXPECT() *MockApiCreateRecordSetRequestMockRecorder {
	return m.recorder
}

// CreateRecordSetPayload mocks base method.
func (m *MockApiCreateRecordSetRequest) CreateRecordSetPayload(createRecordSetPayload dns.CreateRecordSetPayload) dns.ApiCreateRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSetPayload", createRecordSetPayload)
	ret0, _ := ret[0].(dns.ApiCreateRecordSetRequest)
	return ret0
}

// CreateRecordSetPayload indicates an expected call of CreateRecordSetPayload.
func (mr *MockApiCreateRecordSetRequestMockRecorder) CreateRecordSetPayload(createRecordSetPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSetPayload", reflect.TypeOf((*MockApiCreateRecordSetRequest)(nil).CreateRecordSetPayload), createRecordSetPayload)
}

// Execute mocks base method.
func (m *MockApiCreateRecordSetRequest) Execute() (*dns.RecordSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.RecordSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiCreateRecordSetRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiCreateRecordSetRequest)(nil).Execute))
}

// MockApiGetRecordSetRequest is a mock of ApiGetRecordSetRequest interface.
type MockApiGetRecordSetRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiGetRecordSetRequestMockRecorder
	isgomock struct{}
}

// MockApiGetRecordSetRequestMockRecorder is the mock recorder for MockApiGetRecordSetRequest.
type MockApiGetRecordSetRequestMockRecorder struct {
	mock *MockApiGetRecordSetRequest
}

// NewMockApiGetRecordSetRequest creates a new mock instance.
func NewMockApiGetRecordSetRequest(ctrl *gomock.Controller) *MockApiGetRecordSetRequest {
	mock := &MockApiGetRecordSetRequest{ctrl: ctrl}
	mock.recorder = &MockApiGetRecordSetRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiGetRecordSetRequest) EXPECT() *MockApiGetRecordSetRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiGetRecordSetRequest) Execute() (*dns.RecordSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.RecordSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiGetRecordSetRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiGetRecordSetRequest)(nil).Execute))
}

// MockApiPartialUpdateRecordSetRequest is a mock of ApiPartialUpdateRecordSetRequest interface.
type MockApiPartialUpdateRecordSetRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiPartialUpdateRecordSetRequestMockRecorder
	isgomock struct{}
}

// MockApiPartialUpdateRecordSetRequestMockRecorder is the mock recorder for MockApiPartialUpdateRecordSetRequest.
type MockApiPartialUpdateRecordSetRequestMockRecorder struct {
	mock *MockApiPartialUpdateRecordSetRequest
}

// NewMockApiPartialUpdateRecordSetRequest creates a new mock instance.
func NewMockApiPartialUpdateRecordSetRequest(ctrl *gomock.Controller) *MockApiPartialUpdateRecordSetRequest {
	mock := &MockApiPartialUpdateRecordSetRequest{ctrl: ctrl}
	mock.recorder = &MockApiPartialUpdateRecordSetRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiPartialUpdateRecordSetRequest) EXPECT() *MockApiPartialUpdateRecordSetRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiPartialUpdateRecordSetRequest) Execute() (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiPartialUpdateRecordSetRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiPartialUpdateRecordSetRequest)(nil).Execute))
}

// PartialUpdateRecordSetPayload mocks base method.
func (m *MockApiPartialUpdateRecordSetRequest) PartialUpdateRecordSetPayload(partialUpdateRecordSetPayload dns.PartialUpdateRecordSetPayload) dns.ApiPartialUpdateRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordSetPayload", partialUpdateRecordSetPayload)
	ret0, _ := ret[0].(dns.ApiPartialUpdateRecordSetRequest)
	return ret0
}

// PartialUpdateRecordSetPayload indicates an expected call of PartialUpdateRecordSetPayload.
func (mr *MockApiPartialUpdateRecordSetRequestMockRecorder) PartialUpdateRecordSetPayload(partialUpdateRecordSetPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordSetPayload", reflect.TypeOf((*MockApiPartialUpdateRecordSetRequest)(nil).PartialUpdateRecordSetPayload), partialUpdateRecordSetPayload)
}

// MockApiDeleteRecordSetRequest is a mock of ApiDeleteRecordSetRequest interface.
type MockApiDeleteRecordSetRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiDeleteRecordSetRequestMockRecorder
	isgomock struct{}
}

// MockApiDeleteRecordSetRequestMockRecorder is the mock recorder for MockApiDeleteRecordSetRequest.
type MockApiDeleteRecordSetRequestMockRecorder struct {
	mock *MockApiDeleteRecordSetRequest
}

// NewMockApiDeleteRecordSetRequest creates a new mock instance.
func NewMockApiDeleteRecordSetRequest(ctrl *gomock.Controller) *MockApiDeleteRecordSetRequest {
	mock := &MockApiDeleteRecordSetRequest{ctrl: ctrl}
	mock.recorder = &MockApiDeleteRecordSetRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiDeleteRecordSetRequest) EXPECT() *MockApiDeleteRecordSetRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiDeleteRecordSetRequest) Execute() (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiDeleteRecordSetRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiDeleteRecordSetRequest)(nil).Execute))
}

// MockApiGetZoneRequest is a mock of ApiGetZoneRequest interface.
type MockApiGetZoneRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiGetZoneRequestMockRecorder
	isgomock struct{}
}

// MockApiGetZoneRequestMockRecorder is the mock recorder for MockApiGetZoneRequest.
type MockApiGetZoneRequestMockRecorder struct {
	mock *MockApiGetZoneRequest
}

// NewMockApiGetZoneRequest creates a new mock instance.
func NewMockApiGetZoneRequest(ctrl *gomock.Controller) *MockApiGetZoneRequest {
	mock := &MockApiGetZoneRequest{ctrl: ctrl}
	mock.recorder = &MockApiGetZoneRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiGetZoneRequest) EXPECT() *MockApiGetZoneRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiGetZoneRequest) Execute() (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiGetZoneRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiGetZoneRequest)(nil).Execute))
}
