// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/dns (interfaces: ApiCreateZoneRequest,ApiGetZoneRequest,ApiPartialUpdateZoneRequest,ApiDeleteZoneRequest)
//
// Generated by this command:
//
//	mockgen -destination=./mock/requests.go -package=mock_zone github.com/stackitcloud/stackit-sdk-go/services/dns ApiCreateZoneRequest,ApiGetZoneRequest,ApiPartialUpdateZoneRequest,ApiDeleteZoneRequest
//

// Package mock_zone is a generated GoMock package.
package mock_zone

import (
	reflect "reflect"

	dns "github.com/stackitcloud/stackit-sdk-go/services/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockApiCreateZoneRequest is a mock of ApiCreateZoneRequest interface.
type MockApiCreateZoneRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiCreateZoneRequestMockRecorder
	isgomock struct{}
}

// MockApiCreateZoneRequestMockRecorder is the mock recorder for MockApiCreateZoneRequest.
type MockApiCreateZoneRequestMockRecorder struct {
	mock *MockApiCreateZoneRequest
}

// NewMockApiCreateZoneRequest creates a new mock instance.
func NewMockApiCreateZoneRequest(ctrl *gomock.Controller) *MockApiCreateZoneRequest {
	mock := &MockApiCreateZoneRequest{ctrl: ctrl}
	mock.recorder = &MockApiCreateZoneRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiCreateZoneRequest) EXPECT() *MockApiCreateZoneRequestMockRecorder {
	return m.recorder
}

// CreateZonePayload mocks base method.
func (m *MockApiCreateZoneRequest) CreateZonePayload(createZonePayload dns.CreateZonePayload) dns.ApiCreateZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZonePayload", createZonePayload)
	ret0, _ := ret[0].(dns.ApiCreateZoneRequest)
	return ret0
}

// CreateZonePayload indicates an expected call of CreateZonePayload.
func (mr *MockApiCreateZoneRequestMockRecorder) CreateZonePayload(createZonePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZonePayload", reflect.TypeOf((*MockApiCreateZoneRequest)(nil).CreateZonePayload), createZonePayload)
}

// Execute mocks base method.
func (m *MockApiCreateZoneRequest) Execute() (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiCreateZoneRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiCreateZoneRequest)(nil).Execute))
}

// MockApiGetZoneRequest is a mock of ApiGetZoneRequest interface.
type MockApiGetZoneRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiGetZoneRequestMockRecorder
	isgomock struct{}
}

// MockApiGetZoneRequestMockRecorder is the mock recorder for MockApiGetZoneRequest.
type MockApiGetZoneRequestMockRecorder struct {
	mock *MockApiGetZoneRequest
}

// NewMockApiGetZoneRequest creates a new mock instance.
func NewMockApiGetZoneRequest(ctrl *gomock.Controller) *MockApiGetZoneRequest {
	mock := &MockApiGetZoneRequest{ctrl: ctrl}
	mock.recorder = &MockApiGetZoneRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiGetZoneRequest) EXPECT() *MockApiGetZoneRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiGetZoneRequest) Execute() (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiGetZoneRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiGetZoneRequest)(nil).Execute))
}

// MockApiPartialUpdateZoneRequest is a mock of ApiPartialUpdateZoneRequest interface.
type MockApiPartialUpdateZoneRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiPartialUpdateZoneRequestMockRecorder
	isgomock struct{}
}

// MockApiPartialUpdateZoneRequestMockRecorder is the mock recorder for MockApiPartialUpdateZoneRequest.
type MockApiPartialUpdateZoneRequestMockRecorder struct {
	mock *MockApiPartialUpdateZoneRequest
}

// NewMockApiPartialUpdateZoneRequest creates a new mock instance.
func NewMockApiPartialUpdateZoneRequest(ctrl *gomock.Controller) *MockApiPartialUpdateZoneRequest {
	mock := &MockApiPartialUpdateZoneRequest{ctrl: ctrl}
	mock.recorder = &MockApiPartialUpdateZoneRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiPartialUpdateZoneRequest) EXPECT() *MockApiPartialUpdateZoneRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiPartialUpdateZoneRequest) Execute() (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiPartialUpdateZoneRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiPartialUpdateZoneRequest)(nil).Execute))
}

// PartialUpdateZonePayload mocks base method.
func (m *MockApiPartialUpdateZoneRequest) PartialUpdateZonePayload(partialUpdateZonePayload dns.PartialUpdateZonePayload) dns.ApiPartialUpdateZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateZonePayload", partialUpdateZonePayload)
	ret0, _ := ret[0].(dns.ApiPartialUpdateZoneRequest)
	return ret0
}

// PartialUpdateZonePayload indicates an expected call of PartialUpdateZonePayload.
func (mr *MockApiPartialUpdateZoneRequestMockRecorder) PartialUpdateZonePayload(partialUpdateZonePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateZonePayload", reflect.TypeOf((*MockApiPartialUpdateZoneRequest)(nil).PartialUpdateZonePayload), partialUpdateZonePayload)
}

// MockApiDeleteZoneRequest is a mock of ApiDeleteZoneRequest interface.
type MockApiDeleteZoneRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiDeleteZoneRequestMockRecorder
	isgomock struct{}
}

// MockApiDeleteZoneRequestMockRecorder is the mock recorder for MockApiDeleteZoneRequest.
type MockApiDeleteZoneRequestMockRecorder struct {
	mock *MockApiDeleteZoneRequest
}

// NewMockApiDeleteZoneRequest creates a new mock instance.
func NewMockApiDeleteZoneRequest(ctrl *gomock.Controller) *MockApiDeleteZoneRequest {
	mock := &MockApiDeleteZoneRequest{ctrl: ctrl}
	mock.recorder = &MockApiDeleteZoneRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiDeleteZoneRequest) EXPECT() *MockApiDeleteZoneRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiDeleteZoneRequest) Execute() (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiDeleteZoneRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiDeleteZoneRequest)(nil).Execute))
}
