// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/dns (interfaces: DefaultApi)
//
// Generated by this command:
//
//	mockgen -destination=./mock/zone.go -package=mock_zone github.com/stackitcloud/stackit-sdk-go/services/dns DefaultApi
//

// Package mock_zone is a generated GoMock package.
package mock_zone

import (
	context "context"
	reflect "reflect"

	dns "github.com/stackitcloud/stackit-sdk-go/services/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultApi is a mock of DefaultApi interface.
type MockDefaultApi struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultApiMockRecorder
	isgomock struct{}
}

// MockDefaultApiMockRecorder is the mock recorder for MockDefaultApi.
type MockDefaultApiMockRecorder struct {
	mock *MockDefaultApi
}

// NewMockDefaultApi creates a new mock instance.
func NewMockDefaultApi(ctrl *gomock.Controller) *MockDefaultApi {
	mock := &MockDefaultApi{ctrl: ctrl}
	mock.recorder = &MockDefaultApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultApi) EXPECT() *MockDefaultApiMockRecorder {
	return m.recorder
}

// CloneZone mocks base method.
func (m *MockDefaultApi) CloneZone(ctx context.Context, projectId, zoneId string) dns.ApiCloneZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiCloneZoneRequest)
	return ret0
}

// CloneZone indicates an expected call of CloneZone.
func (mr *MockDefaultApiMockRecorder) CloneZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneZone", reflect.TypeOf((*MockDefaultApi)(nil).CloneZone), ctx, projectId, zoneId)
}

// CloneZoneExecute mocks base method.
func (m *MockDefaultApi) CloneZoneExecute(ctx context.Context, projectId, zoneId string) (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneZoneExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneZoneExecute indicates an expected call of CloneZoneExecute.
func (mr *MockDefaultApiMockRecorder) CloneZoneExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).CloneZoneExecute), ctx, projectId, zoneId)
}

// CreateLabel mocks base method.
func (m *MockDefaultApi) CreateLabel(ctx context.Context, projectId, zoneId string) dns.ApiCreateLabelRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiCreateLabelRequest)
	return ret0
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockDefaultApiMockRecorder) CreateLabel(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockDefaultApi)(nil).CreateLabel), ctx, projectId, zoneId)
}

// CreateLabelExecute mocks base method.
func (m *MockDefaultApi) CreateLabelExecute(ctx context.Context, projectId, zoneId string) (*dns.CreateLabelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabelExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.CreateLabelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabelExecute indicates an expected call of CreateLabelExecute.
func (mr *MockDefaultApiMockRecorder) CreateLabelExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabelExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateLabelExecute), ctx, projectId, zoneId)
}

// CreateMoveCode mocks base method.
func (m *MockDefaultApi) CreateMoveCode(ctx context.Context, projectId, zoneId string) dns.ApiCreateMoveCodeRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMoveCode", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiCreateMoveCodeRequest)
	return ret0
}

// CreateMoveCode indicates an expected call of CreateMoveCode.
func (mr *MockDefaultApiMockRecorder) CreateMoveCode(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMoveCode", reflect.TypeOf((*MockDefaultApi)(nil).CreateMoveCode), ctx, projectId, zoneId)
}

// CreateMoveCodeExecute mocks base method.
func (m *MockDefaultApi) CreateMoveCodeExecute(ctx context.Context, projectId, zoneId string) (*dns.MoveCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMoveCodeExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.MoveCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMoveCodeExecute indicates an expected call of CreateMoveCodeExecute.
func (mr *MockDefaultApiMockRecorder) CreateMoveCodeExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMoveCodeExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateMoveCodeExecute), ctx, projectId, zoneId)
}

// CreateRecordSet mocks base method.
func (m *MockDefaultApi) CreateRecordSet(ctx context.Context, projectId, zoneId string) dns.ApiCreateRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSet", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiCreateRecordSetRequest)
	return ret0
}

// CreateRecordSet indicates an expected call of CreateRecordSet.
func (mr *MockDefaultApiMockRecorder) CreateRecordSet(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSet", reflect.TypeOf((*MockDefaultApi)(nil).CreateRecordSet), ctx, projectId, zoneId)
}

// CreateRecordSetExecute mocks base method.
func (m *MockDefaultApi) CreateRecordSetExecute(ctx context.Context, projectId, zoneId string) (*dns.RecordSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSetExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.RecordSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecordSetExecute indicates an expected call of CreateRecordSetExecute.
func (mr *MockDefaultApiMockRecorder) CreateRecordSetExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSetExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateRecordSetExecute), ctx, projectId, zoneId)
}

// CreateZone mocks base method.
func (m *MockDefaultApi) CreateZone(ctx context.Context, projectId string) dns.ApiCreateZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZone", ctx, projectId)
	ret0, _ := ret[0].(dns.ApiCreateZoneRequest)
	return ret0
}

// CreateZone indicates an expected call of CreateZone.
func (mr *MockDefaultApiMockRecorder) CreateZone(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZone", reflect.TypeOf((*MockDefaultApi)(nil).CreateZone), ctx, projectId)
}

// CreateZoneExecute mocks base method.
func (m *MockDefaultApi) CreateZoneExecute(ctx context.Context, projectId string) (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZoneExecute", ctx, projectId)
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateZoneExecute indicates an expected call of CreateZoneExecute.
func (mr *MockDefaultApiMockRecorder) CreateZoneExecute(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).CreateZoneExecute), ctx, projectId)
}

// DeleteLabel mocks base method.
func (m *MockDefaultApi) DeleteLabel(ctx context.Context, projectId, zoneId, key string) dns.ApiDeleteLabelRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLabel", ctx, projectId, zoneId, key)
	ret0, _ := ret[0].(dns.ApiDeleteLabelRequest)
	return ret0
}

// DeleteLabel indicates an expected call of DeleteLabel.
func (mr *MockDefaultApiMockRecorder) DeleteLabel(ctx, projectId, zoneId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLabel", reflect.TypeOf((*MockDefaultApi)(nil).DeleteLabel), ctx, projectId, zoneId, key)
}

// DeleteLabelExecute mocks base method.
func (m *MockDefaultApi) DeleteLabelExecute(ctx context.Context, projectId, zoneId, key string) (*dns.DeleteLabelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLabelExecute", ctx, projectId, zoneId, key)
	ret0, _ := ret[0].(*dns.DeleteLabelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLabelExecute indicates an expected call of DeleteLabelExecute.
func (mr *MockDefaultApiMockRecorder) DeleteLabelExecute(ctx, projectId, zoneId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLabelExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteLabelExecute), ctx, projectId, zoneId, key)
}

// DeleteMoveCode mocks base method.
func (m *MockDefaultApi) DeleteMoveCode(ctx context.Context, projectId, zoneId string) dns.ApiDeleteMoveCodeRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMoveCode", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiDeleteMoveCodeRequest)
	return ret0
}

// DeleteMoveCode indicates an expected call of DeleteMoveCode.
func (mr *MockDefaultApiMockRecorder) DeleteMoveCode(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMoveCode", reflect.TypeOf((*MockDefaultApi)(nil).DeleteMoveCode), ctx, projectId, zoneId)
}

// DeleteMoveCodeExecute mocks base method.
func (m *MockDefaultApi) DeleteMoveCodeExecute(ctx context.Context, projectId, zoneId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMoveCodeExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMoveCodeExecute indicates an expected call of DeleteMoveCodeExecute.
func (mr *MockDefaultApiMockRecorder) DeleteMoveCodeExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMoveCodeExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteMoveCodeExecute), ctx, projectId, zoneId)
}

// DeleteRecordSet mocks base method.
func (m *MockDefaultApi) DeleteRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) dns.ApiDeleteRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(dns.ApiDeleteRecordSetRequest)
	return ret0
}

// DeleteRecordSet indicates an expected call of DeleteRecordSet.
func (mr *MockDefaultApiMockRecorder) DeleteRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSet", reflect.TypeOf((*MockDefaultApi)(nil).DeleteRecordSet), ctx, projectId, zoneId, rrSetId)
}

// DeleteRecordSetExecute mocks base method.
func (m *MockDefaultApi) DeleteRecordSetExecute(ctx context.Context, projectId, zoneId, rrSetId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSetExecute", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecordSetExecute indicates an expected call of DeleteRecordSetExecute.
func (mr *MockDefaultApiMockRecorder) DeleteRecordSetExecute(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSetExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteRecordSetExecute), ctx, projectId, zoneId, rrSetId)
}

// DeleteZone mocks base method.
func (m *MockDefaultApi) DeleteZone(ctx context.Context, projectId, zoneId string) dns.ApiDeleteZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiDeleteZoneRequest)
	return ret0
}

// DeleteZone indicates an expected call of DeleteZone.
func (mr *MockDefaultApiMockRecorder) DeleteZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZone", reflect.TypeOf((*MockDefaultApi)(nil).DeleteZone), ctx, projectId, zoneId)
}

// DeleteZoneExecute mocks base method.
func (m *MockDefaultApi) DeleteZoneExecute(ctx context.Context, projectId, zoneId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZoneExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteZoneExecute indicates an expected call of DeleteZoneExecute.
func (mr *MockDefaultApiMockRecorder) DeleteZoneExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).DeleteZoneExecute), ctx, projectId, zoneId)
}

// ExportRecordSets mocks base method.
func (m *MockDefaultApi) ExportRecordSets(ctx context.Context, projectId, zoneId string) dns.ApiExportRecordSetsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRecordSets", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiExportRecordSetsRequest)
	return ret0
}

// ExportRecordSets indicates an expected call of ExportRecordSets.
func (mr *MockDefaultApiMockRecorder) ExportRecordSets(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRecordSets", reflect.TypeOf((*MockDefaultApi)(nil).ExportRecordSets), ctx, projectId, zoneId)
}

// ExportRecordSetsExecute mocks base method.
func (m *MockDefaultApi) ExportRecordSetsExecute(ctx context.Context, projectId, zoneId string) (*dns.ZoneDataExchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRecordSetsExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ZoneDataExchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportRecordSetsExecute indicates an expected call of ExportRecordSetsExecute.
func (mr *MockDefaultApiMockRecorder) ExportRecordSetsExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRecordSetsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ExportRecordSetsExecute), ctx, projectId, zoneId)
}

// GetRecordSet mocks base method.
func (m *MockDefaultApi) GetRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) dns.ApiGetRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(dns.ApiGetRecordSetRequest)
	return ret0
}

// GetRecordSet indicates an expected call of GetRecordSet.
func (mr *MockDefaultApiMockRecorder) GetRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordSet", reflect.TypeOf((*MockDefaultApi)(nil).GetRecordSet), ctx, projectId, zoneId, rrSetId)
}

// GetRecordSetExecute mocks base method.
func (m *MockDefaultApi) GetRecordSetExecute(ctx context.Context, projectId, zoneId, rrSetId string) (*dns.RecordSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordSetExecute", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(*dns.RecordSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordSetExecute indicates an expected call of GetRecordSetExecute.
func (mr *MockDefaultApiMockRecorder) GetRecordSetExecute(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordSetExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetRecordSetExecute), ctx, projectId, zoneId, rrSetId)
}

// GetZone mocks base method.
func (m *MockDefaultApi) GetZone(ctx context.Context, projectId, zoneId string) dns.ApiGetZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiGetZoneRequest)
	return ret0
}

// GetZone indicates an expected call of GetZone.
func (mr *MockDefaultApiMockRecorder) GetZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZone", reflect.TypeOf((*MockDefaultApi)(nil).GetZone), ctx, projectId, zoneId)
}

// GetZoneExecute mocks base method.
func (m *MockDefaultApi) GetZoneExecute(ctx context.Context, projectId, zoneId string) (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneExecute indicates an expected call of GetZoneExecute.
func (mr *MockDefaultApiMockRecorder) GetZoneExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).GetZoneExecute), ctx, projectId, zoneId)
}

// ImportRecordSets mocks base method.
func (m *MockDefaultApi) ImportRecordSets(ctx context.Context, projectId, zoneId string) dns.ApiImportRecordSetsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportRecordSets", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiImportRecordSetsRequest)
	return ret0
}

// ImportRecordSets indicates an expected call of ImportRecordSets.
func (mr *MockDefaultApiMockRecorder) ImportRecordSets(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportRecordSets", reflect.TypeOf((*MockDefaultApi)(nil).ImportRecordSets), ctx, projectId, zoneId)
}

// ImportRecordSetsExecute mocks base method.
func (m *MockDefaultApi) ImportRecordSetsExecute(ctx context.Context, projectId, zoneId string) (*dns.ImportRecordSetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportRecordSetsExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ImportRecordSetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportRecordSetsExecute indicates an expected call of ImportRecordSetsExecute.
func (mr *MockDefaultApiMockRecorder) ImportRecordSetsExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportRecordSetsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ImportRecordSetsExecute), ctx, projectId, zoneId)
}

// ListLabels mocks base method.
func (m *MockDefaultApi) ListLabels(ctx context.Context, projectId, zoneId string) dns.ApiListLabelsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiListLabelsRequest)
	return ret0
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockDefaultApiMockRecorder) ListLabels(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockDefaultApi)(nil).ListLabels), ctx, projectId, zoneId)
}

// ListLabelsExecute mocks base method.
func (m *MockDefaultApi) ListLabelsExecute(ctx context.Context, projectId, zoneId string) (*dns.ListLabelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabelsExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ListLabelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLabelsExecute indicates an expected call of ListLabelsExecute.
func (mr *MockDefaultApiMockRecorder) ListLabelsExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabelsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListLabelsExecute), ctx, projectId, zoneId)
}

// ListRecordSets mocks base method.
func (m *MockDefaultApi) ListRecordSets(ctx context.Context, projectId, zoneId string) dns.ApiListRecordSetsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordSets", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiListRecordSetsRequest)
	return ret0
}

// ListRecordSets indicates an expected call of ListRecordSets.
func (mr *MockDefaultApiMockRecorder) ListRecordSets(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordSets", reflect.TypeOf((*MockDefaultApi)(nil).ListRecordSets), ctx, projectId, zoneId)
}

// ListRecordSetsExecute mocks base method.
func (m *MockDefaultApi) ListRecordSetsExecute(ctx context.Context, projectId, zoneId string) (*dns.ListRecordSetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordSetsExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ListRecordSetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecordSetsExecute indicates an expected call of ListRecordSetsExecute.
func (mr *MockDefaultApiMockRecorder) ListRecordSetsExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordSetsExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListRecordSetsExecute), ctx, projectId, zoneId)
}

// ListZones mocks base method.
func (m *MockDefaultApi) ListZones(ctx context.Context, projectId string) dns.ApiListZonesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZones", ctx, projectId)
	ret0, _ := ret[0].(dns.ApiListZonesRequest)
	return ret0
}

// ListZones indicates an expected call of ListZones.
func (mr *MockDefaultApiMockRecorder) ListZones(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZones", reflect.TypeOf((*MockDefaultApi)(nil).ListZones), ctx, projectId)
}

// ListZonesExecute mocks base method.
func (m *MockDefaultApi) ListZonesExecute(ctx context.Context, projectId string) (*dns.ListZonesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZonesExecute", ctx, projectId)
	ret0, _ := ret[0].(*dns.ListZonesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListZonesExecute indicates an expected call of ListZonesExecute.
func (mr *MockDefaultApiMockRecorder) ListZonesExecute(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZonesExecute", reflect.TypeOf((*MockDefaultApi)(nil).ListZonesExecute), ctx, projectId)
}

// MoveZone mocks base method.
func (m *MockDefaultApi) MoveZone(ctx context.Context, projectId string) dns.ApiMoveZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveZone", ctx, projectId)
	ret0, _ := ret[0].(dns.ApiMoveZoneRequest)
	return ret0
}

// MoveZone indicates an expected call of MoveZone.
func (mr *MockDefaultApiMockRecorder) MoveZone(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveZone", reflect.TypeOf((*MockDefaultApi)(nil).MoveZone), ctx, projectId)
}

// MoveZoneExecute mocks base method.
func (m *MockDefaultApi) MoveZoneExecute(ctx context.Context, projectId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveZoneExecute", ctx, projectId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveZoneExecute indicates an expected call of MoveZoneExecute.
func (mr *MockDefaultApiMockRecorder) MoveZoneExecute(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).MoveZoneExecute), ctx, projectId)
}

// PartialUpdateRecord mocks base method.
func (m *MockDefaultApi) PartialUpdateRecord(ctx context.Context, projectId, zoneId, rrSetId string) dns.ApiPartialUpdateRecordRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecord", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(dns.ApiPartialUpdateRecordRequest)
	return ret0
}

// PartialUpdateRecord indicates an expected call of PartialUpdateRecord.
func (mr *MockDefaultApiMockRecorder) PartialUpdateRecord(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecord", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateRecord), ctx, projectId, zoneId, rrSetId)
}

// PartialUpdateRecordExecute mocks base method.
func (m *MockDefaultApi) PartialUpdateRecordExecute(ctx context.Context, projectId, zoneId, rrSetId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordExecute", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialUpdateRecordExecute indicates an expected call of PartialUpdateRecordExecute.
func (mr *MockDefaultApiMockRecorder) PartialUpdateRecordExecute(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordExecute", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateRecordExecute), ctx, projectId, zoneId, rrSetId)
}

// PartialUpdateRecordSet mocks base method.
func (m *MockDefaultApi) PartialUpdateRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) dns.ApiPartialUpdateRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(dns.ApiPartialUpdateRecordSetRequest)
	return ret0
}

// PartialUpdateRecordSet indicates an expected call of PartialUpdateRecordSet.
func (mr *MockDefaultApiMockRecorder) PartialUpdateRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordSet", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateRecordSet), ctx, projectId, zoneId, rrSetId)
}

// PartialUpdateRecordSetExecute mocks base method.
func (m *MockDefaultApi) PartialUpdateRecordSetExecute(ctx context.Context, projectId, zoneId, rrSetId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordSetExecute", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialUpdateRecordSetExecute indicates an expected call of PartialUpdateRecordSetExecute.
func (mr *MockDefaultApiMockRecorder) PartialUpdateRecordSetExecute(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordSetExecute", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateRecordSetExecute), ctx, projectId, zoneId, rrSetId)
}

// PartialUpdateZone mocks base method.
func (m *MockDefaultApi) PartialUpdateZone(ctx context.Context, projectId, zoneId string) dns.ApiPartialUpdateZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiPartialUpdateZoneRequest)
	return ret0
}

// PartialUpdateZone indicates an expected call of PartialUpdateZone.
func (mr *MockDefaultApiMockRecorder) PartialUpdateZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateZone", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateZone), ctx, projectId, zoneId)
}

// PartialUpdateZoneExecute mocks base method.
func (m *MockDefaultApi) PartialUpdateZoneExecute(ctx context.Context, projectId, zoneId string) (*dns.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateZoneExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialUpdateZoneExecute indicates an expected call of PartialUpdateZoneExecute.
func (mr *MockDefaultApiMockRecorder) PartialUpdateZoneExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).PartialUpdateZoneExecute), ctx, projectId, zoneId)
}

// RestoreRecordSet mocks base method.
func (m *MockDefaultApi) RestoreRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) dns.ApiRestoreRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(dns.ApiRestoreRecordSetRequest)
	return ret0
}

// RestoreRecordSet indicates an expected call of RestoreRecordSet.
func (mr *MockDefaultApiMockRecorder) RestoreRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreRecordSet", reflect.TypeOf((*MockDefaultApi)(nil).RestoreRecordSet), ctx, projectId, zoneId, rrSetId)
}

// RestoreRecordSetExecute mocks base method.
func (m *MockDefaultApi) RestoreRecordSetExecute(ctx context.Context, projectId, zoneId, rrSetId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreRecordSetExecute", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreRecordSetExecute indicates an expected call of RestoreRecordSetExecute.
func (mr *MockDefaultApiMockRecorder) RestoreRecordSetExecute(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreRecordSetExecute", reflect.TypeOf((*MockDefaultApi)(nil).RestoreRecordSetExecute), ctx, projectId, zoneId, rrSetId)
}

// RestoreZone mocks base method.
func (m *MockDefaultApi) RestoreZone(ctx context.Context, projectId, zoneId string) dns.ApiRestoreZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiRestoreZoneRequest)
	return ret0
}

// RestoreZone indicates an expected call of RestoreZone.
func (mr *MockDefaultApiMockRecorder) RestoreZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreZone", reflect.TypeOf((*MockDefaultApi)(nil).RestoreZone), ctx, projectId, zoneId)
}

// RestoreZoneExecute mocks base method.
func (m *MockDefaultApi) RestoreZoneExecute(ctx context.Context, projectId, zoneId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreZoneExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreZoneExecute indicates an expected call of RestoreZoneExecute.
func (mr *MockDefaultApiMockRecorder) RestoreZoneExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).RestoreZoneExecute), ctx, projectId, zoneId)
}

// RetrieveZone mocks base method.
func (m *MockDefaultApi) RetrieveZone(ctx context.Context, projectId, zoneId string) dns.ApiRetrieveZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiRetrieveZoneRequest)
	return ret0
}

// RetrieveZone indicates an expected call of RetrieveZone.
func (mr *MockDefaultApiMockRecorder) RetrieveZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveZone", reflect.TypeOf((*MockDefaultApi)(nil).RetrieveZone), ctx, projectId, zoneId)
}

// RetrieveZoneExecute mocks base method.
func (m *MockDefaultApi) RetrieveZoneExecute(ctx context.Context, projectId, zoneId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveZoneExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveZoneExecute indicates an expected call of RetrieveZoneExecute.
func (mr *MockDefaultApiMockRecorder) RetrieveZoneExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveZoneExecute", reflect.TypeOf((*MockDefaultApi)(nil).RetrieveZoneExecute), ctx, projectId, zoneId)
}

// ValidateMoveCode mocks base method.
func (m *MockDefaultApi) ValidateMoveCode(ctx context.Context, projectId, zoneId string) dns.ApiValidateMoveCodeRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMoveCode", ctx, projectId, zoneId)
	ret0, _ := ret[0].(dns.ApiValidateMoveCodeRequest)
	return ret0
}

// ValidateMoveCode indicates an expected call of ValidateMoveCode.
func (mr *MockDefaultApiMockRecorder) ValidateMoveCode(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMoveCode", reflect.TypeOf((*MockDefaultApi)(nil).ValidateMoveCode), ctx, projectId, zoneId)
}

// ValidateMoveCodeExecute mocks base method.
func (m *MockDefaultApi) ValidateMoveCodeExecute(ctx context.Context, projectId, zoneId string) (*dns.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMoveCodeExecute", ctx, projectId, zoneId)
	ret0, _ := ret[0].(*dns.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateMoveCodeExecute indicates an expected call of ValidateMoveCodeExecute.
func (mr *MockDefaultApiMockRecorder) ValidateMoveCodeExecute(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMoveCodeExecute", reflect.TypeOf((*MockDefaultApi)(nil).ValidateMoveCodeExecute), ctx, projectId, zoneId)
}
